version: '3.9'
services:
  frontend:
    build: frontend/.
    image: wevertoncampos/frontend:latest
    container_name: frontend
    restart: always
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - '80:80'

  api:
    build: api/.
    image: wevertoncampos/backend:latest
    container_name: backend
    restart: always
    volumes:
      - ./api:/usr/share/nginx/html
    ports:
      - '8080:8080'

  mysql:
    build: .
    image: wevertoncampos/mysql:latest
    container_name: mysql
    restart: always
    volumes:
      - ./dbdata:/var/lib/mysql
    ports:
      - '3306:3306'