version: '3.7'
services:
  web:
    image: php:8.1-apache
    container_name: php-apache
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
    networks:
      vpc1:
        ipv4_address: 10.0.0.2

networks:
  vpc1:
    driver: bridge
    ipam:
     config:
      - subnet: 10.0.0.0/16
        gateway: 10.0.0.1



